name: Rewrite installers
run-name: Rewrite installers ${{ inputs.version-filter && inputs.version-filter || 'all' }}

on:
  workflow_dispatch:
    inputs:
      maven-artifact:
        default: net.neoforged:neoforge
        type: string
        description: The artifact of the installers to rewrite
        required: true
      version-filter:
        type: string
        description: The filter (prefix) to filter versions using
      dry:
        type: boolean
        default: false
        description: Trigger a dry run, only logging the versions
      update-installer-rewrite:
        type: boolean
        default: false
        description: Rewrite the installers to the latest version
      checksums-only:
        type: boolean
        default: false
        description: Only update checksums

jobs:
  rewrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true
      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - name: Build rewriter
        run: ./gradlew :shadowJar
      - name: Backup jars
        if: ${{ inputs.dry == false || inputs.checksums-only == false }}
        run: |
          java -Xmx6G -jar build/libs/rewriter.jar --maven-url https://maven-direct.neoforged.net/releases/ --maven-user ${{ secrets.MAVEN_USER }} --maven-password ${{ secrets.MAVEN_PASSWORD }} --maven-path ${{ inputs.maven-artifact }} --backup=installerbackup ${{ inputs.version-filter && format('--filter={0}', inputs.version-filter) || '' }} --thread-limit=10 --backup-only
      - uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: backup
          path: installerbackup/
      - name: Rewrite jars
        run: |
          java -Xmx6G -jar build/libs/rewriter.jar --maven-url https://maven-direct.neoforged.net/releases/ --maven-user ${{ secrets.MAVEN_USER }} --maven-password ${{ secrets.MAVEN_PASSWORD }} --maven-path ${{ inputs.maven-artifact }} --backup=installerbackup2 ${{ inputs.dry && '--dry' || '' }} ${{ inputs.version-filter && format('--filter={0}', inputs.version-filter) || '' }} --thread-limit=10 ${{ inputs.update-installer-rewrite && '--installer-version-update' || '' }} ${{ inputs.checksums-only && '--update-checksums' || '' }}
