name: Rewrite installers

on:
  workflow_dispatch:
    inputs:
      maven-artifact:
        default: net.neoforged:neoforge
        type: string
        description: The artifact of the installers to rewrite
        required: true
      version-filter:
        type: string
        description: The filter (prefix) to filter versions using
      dry:
        type: boolean
        default: false
        description: Trigger a dry run, only logging the versions


jobs:
  rewrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true
      - name: Setup Java 21
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
        # language=bash
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_21_X64)" >> "$GITHUB_ENV"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - name: Build rewriter
        run: ./gradlew :shadowJar
      - name: Rewrite jars
        run: |
          java -jar build/libs/rewriter.jar --maven-url https://maven.neoforged.net/releases/ --maven-user ${{ secrets.MAVEN_USER }} --maven-password ${{ secrets.MAVEN_PASSWORD }} --maven-path ${{ inputs.maven-artifact }} --backup installerbackup ${{ inputs.dry && '--dry' || '' }} ${{ inputs.version-filter && ('--filter ' + inputs.version-filter) || '' }} --thread-limit 10

      - uses: actions/upload-artifact@v4
        if: ${{ !inputs.dry }}
        with:
          name: backup
          path: installerbackup/
